### ISSUE TITLE
Newbie question

### ISSUE THREAD

**Issue by Spark50** [EVNotify/EVNotify#167]
Hi all
Looking to use evnotify on my uk kia electric Niro,  after doing some research can I ask couple of questions. 

It has been reported that the power to the obd dongle stops after less than an hour, do you know if this is correct as this would present a problem to me using.

Also reported that it could potentially drain the battery if left on all time,  again is this true. Rather  than keep unplugging the obd dongle, I have found a obd extension cable with a switch would cuts the power to the dongle, anybody know if this would work.

Apologies if posted in wrong part very new to github

**Comment by GPlay97** [comment]
Hey,

thanks for reaching out.

Some dongle stop working, but most of them can run infitely. EVNotify manages it. If EVNotify stops working, on Android this is most likely to energy saving options (they can be turned off). On iOS this is due to restrictions from Apple (currently it's not expected that it will change..).

EVNotify has a standby handler, so if car is off and not charging, it currently goes into deep sleep together with the dongle, so drain prevented.
