### ISSUE TITLE
Support for "Foseal ODB2 bluetooth" ?

### ISSUE THREAD

**Issue by warenbe** [EVNotify/EVNotify#283]
### New issue
- Short description: 

Compatibility with Foseal ODB2 bluetooth reader

- Detailed description:

The application seems to be unable to initialize this dongle.  a short message saying "initializing" appear, then nothing. No error, no warning. the app seem to run correctly but no data are displayed on the screen.
sometime, a battery level appear, but the level is completely wrong.

How can we help to add compatibility with this dongle ? any log ? 

- Can you reproduce it? (_If so, how?_):

yes. each time.

- [ x] critical issue? (_issue, which will affect multiple accounts, 
  an issue which prevents that you can use the app in a normal way,
  bug which makes app unusable, security breach*_) (Yes/No):

yes

The question is: 
do you need any information, any log, etc, that can help to add compatibility with this reader ?
or is it a nogo ?

**Comment by GPlay97** [comment]
On the current app, v2, new dongle support is limited unfortunately due to some technical implementations. However, as mentioned now on the README too, the new app generation v3, is in development and will accept many more dongles (already tested quite a lot and all of them worked there, even under iOS)
