### ISSUE TITLE
Missing Android release tag/APK

### ISSUE THREAD

**Issue by IzzySoft** [EVNotify/EVNotify#287]
On PlayStore, you've released v2.3.0 a while ago. Could you please add the corresponding app with its APK here as well? Thanks!

**Comment by iGadget** [comment]
Interesting... Apparently, I have the latest version from the Play Store installed, but in the app it still says v.2.2.2:00?

**Comment by IzzySoft** [comment]
![image](https://user-images.githubusercontent.com/6781438/197291163-6240802d-ede6-458c-890c-7be2b792e98f.png)

([source](https://www.appbrain.com/app/com.evnotify.app)) Was that update withdrawn then? PlayStore itself also says:

![image](https://user-images.githubusercontent.com/6781438/197291634-b634e84f-db57-448f-80a8-d94863466a57.png)

([source](https://play.google.com/store/apps/details?id=com.evnotify.app&hl=en)) Which means you seem not to have the latest version from there, @iGadget :wink: And here at Github releases, the **3** latest versions are missing. Will you add them, @GPlay97?

**Comment by GPlay97** [comment]
It looks like, I accidentally forgot to update the version number within the app settings page, but it is the latest version, as mentioned.

I just added the latest release now. Since the other ones were mostly patches, I will not add them here again, as the new v2 release will probably be the last v2 release. The upcoming new v3 release is waiting soon for everyone!

**Comment by IzzySoft** [comment]
Thanks a lot! My updater already found it, so the latest version is [available in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.evnotify.app) again. If you grant me another wish, it would be a version without Firebase Analytics so the `Tracking` anti-feature could be dropped :blush:
